she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('category/<str:slug_field>/', views.CategoryView.as_view(), name= 'category')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, UserAccountView, AuthorView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='create-account'),
    path('<int:pk>/', UserAccountView.as_view(),name='user_account'),
    path('author/<int:pk>/', AuthorView.as_view(), name = 'author_profile'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=75) 
    description = models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.name

class NewsStory(models.Model):
    class Meta:
        ordering = ['-pub_date']
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True)
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(blank=True)
   



  
 

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory
from .models import Category

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'image_url', 'category', 'content']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),attrs={'class':'form-control', 'placeholder':'Select a date','type':'date'}),
            }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm 
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
        
class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import NewsStory, Category
from users.models import CustomUser
from .forms import StoryForm



class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        context['all_stories'] = NewsStory.objects.all()
        context['story_authors']= CustomUser.objects.all()
        context['category']= Category.objects.all()
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class CategoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story_category_detail.html'
    context_object_name = 'category'
    slug_field = 'name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = NewsStory.objects.filter(category=self.kwargs['category'])
        return context

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from news.models import NewsStory
from .models import CustomUser
from .forms import CustomUserCreationForm


class CreateAccountView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'registration/create_account.html'

class UserAccountView(generic.DetailView):
	model = CustomUser
	template_name = 'users/user_account_detail.html'
	context_object_name = 'user'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user_stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])
		return context

class AuthorView(generic.DetailView):
	model = CustomUser
	template_name = 'users/author_profile_detail.html'
	context_object_name = 'author'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user_stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])
		return context

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles_news.css' %}">
{% endblock %}

{% block content %}
    
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {%include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <h2>View stories by author:</h2>

    <div id="all-authors">
        {% if story_authors %}
            {% for author in story_authors %}
                <a href=" {% url 'users:author_profile' author.id %}">{{ author }}</a>
                {% endfor %}
            {% else %}
                <p>No authors are available.</p>
        {% endif %}   
    </div>

    <h2>All Stories</h2>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>   
   

{% endblock %}



{% comment %}    
    
{% endcomment %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles_news.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h3>{{ story.title }}</h3>
    <h4>Written by {{ story.author }}</h4>
    <p>Category: {{ story.category }}</p>
    <div id="story-content">
        <p>
        <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {{ story.content|linebreaks }}
        </p>
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles_news.css' %}">
{% endblock %}

{% block content %}

<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image_url %}
            <img src="{{ story.image_url }}">
        {% else %}
            <img src="https://picsum.photos/300?random={{ story.id }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <p>{{ story.pub_date }}</p>
        </div>
    </a>
</div>

{% endblock %}

she_codes_news/news/templates/news/story_category_detail.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles_news.css' %}">
{% endblock %}

{% block content %}

<h2>Stories in category: {{ category }}</h2>
<br/>
<div id="Category">
    {% if categories %}
        {% for story in categories %}
            {% include "news/storyCard.html" with story=story %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %}

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Katrina Italiano">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
            {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>
        {% block content %}{% endblock %}
        <br/>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
      <a href="{% url 'users:user_account' request.user.id %}">Logged in as: {{ user.username }}</a>
      <a href="{% url 'news:newStory' %}">Write new story</a>
      <a href="{% url 'logout' %}">Logout</a>
    
    {% else %}
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'users:create-account' %}">Create account</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/author_profile.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<h2>{{ author }}'s Stories:</h2>
<br/>
<div id="user-stories">
    {% if user_stories %}
        {% for story in user_stories %}
            {% include "news/storyCard.html" with story=story %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %}

she_codes_news/users/templates/users/author_profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles_news.css' %}">
{% endblock %}

{% block content %}

<h2>{{ author }}'s Stories:</h2>
<br/>
<div id="user-stories">
    {% if user_stories %}
        {% for story in user_stories %}
            {% include "news/storyCard.html" with story=story %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %}

she_codes_news/users/templates/users/user_account_detail.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles_news.css' %}">
{% endblock %}

{% block content %}

<h2>{{ user }}</h2>
<br/>
<h3>Your Stories:</h3>
<br/>
<div id="user-stories">
    {% if user_stories %}
        {% for story in user_stories %}
            {% include "news/storyCard.html" with story=story %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %}

she_codes_news/users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ user }}</h2>
<div>
</div>

{% endblock %}